---
language: ruby
cache: bundler
bundler_args: --without development
sudo: false
script: bundle exec rake test
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.1.6
    sudo: required
    dist: trusty
    services: docker
    env: BEAKER_set="ubuntu-16.04"
    script: bundle exec rake beaker
  - rvm: 2.1.6
    sudo: required
    dist: trusty
    services: docker
    env: BEAKER_set="centos-7"
    script: bundle exec rake beaker
